language: php

branches:
  except:
    - /^release-.*$/
    - /^ghgfk-.*$/

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - laminas-mkdoc-theme

env:
  global:
    - EVENT_MANAGER_VERSION="^3.0"
    - SERVICE_MANAGER_VERSION="^3.0.3"
    - SITE_URL: https://docs.laminas.dev/laminas-modulemanager
    - GH_USER_NAME: "Matthew Weier O'Phinney"
    - GH_USER_EMAIL: matthew@weierophinney.net
    - GH_REF: github.com/laminas/laminas-modulemanager.git
    - secure: "HRR08cbsMeb8yqLPY74rM+wTu1WJ1jz/6Dzl6iBEqL7hxAhXXS5SeMkv24GkESz3gPS9HfAGR5FgIJubBN5e77hGJQ/DKyWUHkxv+xEbNifDJt1x5RY6aE9GliqDrJpfE2Xa79A4WheZMGkpZvYzd1nVC0gRIuR22Mg44LaminasCYBc8PxBgeWwGcqlF27agNv9S68BhPWayOa5GxzdO39ucruA4xBtlGflPe6mPuq64MfCn8q6BUtDgXNrI2qRVigxIB2gfzbYSU9OGbXViCmRdAEb9eLWunACXlqcw5V8OHT+2ZM01soRwv8ZXTPCZhdI/uC7eDFM+vW5OrUhO3+0D6t3vOqBJXio2h7hJwzUCq4OVRoJvChGxn3bn+d5xqxKkU7pyMFekIVzAwt/wDijMRnkwfrzhqmHCibu1lI8dUswILNu+uqHTkEm4zw7NVn10lWbogQwFNP9Icg60eMIJ8JPsqeod1/z+v1va3U3jW6wpRqtW0EVwj5MZ8a5AIHF1jrhL0c/B7jAlIpURD7atPUf6ZRhERSO3ckJBQUZBhCC76RimTKx/Z7m8fM2+Ly7ZO5g8IundXGmo35oU6ycUcZcEZR+VJrPHmZN3tUFNtcBdSzVfYYh5l2pdiui/dmc9ql5Pl4pzlavHB8J7pzcBrXM1m9nSEKKxmXdJNalFPWI="

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - CS_CHECK=true
    - php: 5.5
      env:
        - EVENT_MANAGER_VERSION="^2.6.2"
        - SERVICE_MANAGER_VERSION="^2.7.5"
    - php: 5.6
      env:
        - TEST_COVERAGE=true
        - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
        - PATH="$HOME/.local/bin:$PATH"
    - php: 5.6
      env:
        - EVENT_MANAGER_VERSION="^2.6.2"
        - SERVICE_MANAGER_VERSION="^2.7.5"
    - php: 7
    - php: 7
      env:
        - EVENT_MANAGER_VERSION="^2.6.2"
        - SERVICE_MANAGER_VERSION="^2.7.5"
    - php: 7.1
    - php: 7.1
      env:
        - EVENT_MANAGER_VERSION="^2.6.2"
        - SERVICE_MANAGER_VERSION="^2.7.5"
    - php: hhvm
    - php: hhvm
      env:
        - EVENT_MANAGER_VERSION="^2.6.2"
        - SERVICE_MANAGER_VERSION="^2.7.5"
  allow_failures:
    - php: hhvm

before_install:
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls ; fi
  - composer require --no-update "laminas/laminas-eventmanager:$EVENT_MANAGER_VERSION"
  - composer require --dev --no-update "laminas/laminas-servicemanager:$SERVICE_MANAGER_VERSION"

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; else composer test ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi
  - if [[ $DEPLOY_DOCS == "true" && "$TRAVIS_TEST_RESULT" == "0" ]]; then travis_retry curl -sSL https://raw.githubusercontent.com/laminas/laminas-mkdoc-theme/master/theme-installer.sh | bash ; fi

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then echo "Preparing to build and deploy documentation" ; ./laminas-mkdoc-theme/deploy.sh ; echo "Completed deploying documentation" ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer upload-coverage ; fi

notifications:
  email: false
    channels:
      - "irc.freenode.org#laminastalk.dev"
    on_success: change
    on_failure: always
  slack:
    rooms:
      - secure: "FAFyl1egzrcsOB+9cDBWivXdbFzMfE6kN97vLQme4g935bAD+Mgt/PXQoKtAvVm2Sq0kxdXTzXulBfmYh+S+qK4LJbAWF5nsl/QEqdHIsQjvujbuHcvqOVljkHQhvHT9JLZicxQgEfux9Mi+OFkiylakpTro4XtFvT86xGbW8AMeHyLUH1bTGNHvY4og2UJD1LLUdEZQPoxKXxUV0/rC4KK2woaEMTgbhwRoglLv68n5nHHd9s2pSK8p74MIbRF5DpFVtKpHJmruoNgCwSmrtNlKMtrqMPhzNEbvc1IV2id09itaN2+QojSR3yUoUANQ9zORDAIy4BdlIyD+5T4emn+0ONMg9JQVnozOluxWqHZ4VfyCQfBbAA2B1zpdKKzhT1ZAOLWi2aSRw04gknTtM+fnpNOAbMBF9kx2Y4B2U1vMaUdPR92wsVzjuHg9hRpAeBgfrzPfq47cGi0kfVXkO+c/hrLu6AZbtdE6f6OMh7uwNIvs8TqnoDiPLGgutMrl6Ww0znDsL6rtOrzId2FeuzZ7O8LUVtcR6P/NDqRE6TJy/g1c2q1xXni7w/l0SYs+jjtwFvZ++ksQywkNb9C+iZ6xZKxqKDzn3GlpgOg/1oHECd6n4AmssOwWhFDGNrLPiYGhD8z4oYJgLYU36UoUk7TM6jXy/2ASUnGAaY9iqWA="
    on_success: change
    on_failure: always
